### ISSUE TITLE
Verb to fill missing values

### ISSUE THREAD

**Issue by luukvdmeer** [ZGIS/semantique#19]
#### Description

This verb is already added as a "placeholder", but has no implementation yet. There are three different approaches:

- Fill using the assign verb logic: each missing value gets assigned the same value, e.g. -999
- Fill using the smooth verb logic: each missing value is filled by applying a reducer function to a moving window along a given dimension, with the missing value in its center. Do note that this might not fill all missing values if the window size is not large enough (i.e. windows containing only missing values will still return a missing value).
- Fill using interpolation: each missing value is filled by fitting a interpolation function along a given dimension.

**Comment by luukvdmeer** [comment]
@whisperingpixel @dtiede The fill verb is implemented now and fills missing data by interpolation. Interpolation methods to choose from are "nearest", "linear" and "cubic". 2D interpolation over space is also possible, then it will use 2D nearest neighbour, bilinear and bicubic, repspectively. See here the docs: https://zgis.github.io/semantique/_notebooks/verbs.html#Fill

Another way to handle missing data is using the assign verb in combination with the "is_missing" operator. This can assign fixed values to the missing data. See here the docs: https://zgis.github.io/semantique/_notebooks/verbs.html#Assigning-to-nodata-values

This still has to be added to the Sen2Cube frontend

**Comment by dtiede** [comment]
Great, thanks!!
