### ISSUE TITLE
UserWarning raised about renaming dimensions

### ISSUE THREAD

**Issue by loreabad6** [ZGIS/semantique#22]
#### Description
When executing a query with a given context, `space` seems to return a UserWarning:

`UserWarning: rename 'y' to 'y' does not create an index anymore. Try using swap_dims instead or use set_index after rename to create an indexed coordinate.
  space = space.rename({space.rio.y_dim: Y, space.rio.x_dim: X})`

#### Environment information
 - Version of semantique: 0.1.0
 - Versions of rasterio: 1.3.6

**Comment by luukvdmeer** [comment]
This is fixed now with the commits referenced above
